name: gridtest-example

on:
  pull_request:
    branches_ignore: []

jobs:
  gridtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup gridtest conda environment
        run: |
            conda create --quiet --name gridtest
            export PATH="/usr/share/miniconda/bin:$PATH"
            source activate gridtest
            # conda install --channel conda-forge gridtest
            pip install -e .

      - name: Run gridtest and generate web report
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate gridtest
          gridtest test examples/interface/gridtest.yml --save-web report/

      - name: Upload gridtest report as artifact
        uses: actions/upload-artifact@v1
        with:
          name: gridtest
          path: report

